### ISSUE TITLE
.

### ISSUE THREAD

**Issue by ghost** [shedaniel/CustomSelectionBox-New#1]

**Comment by shedaniel** [comment]
Noticed. I will try to fix this asap

**Comment by shedaniel** [comment]
I don't think that I will fix this.
It is not really easy.

**Comment by Blue-Beaker** [comment]
This is the bug of most of the shader packs that incorrectly renders things like the selection box(Vanilla ones also affected)

**Comment by shedaniel** [comment]
Custom Selection Box overrides the whole selection box rendering, there isn't a better way to do this except asm.
