### ISSUE TITLE
[Issue][1.14] Break Animation dosen't work

### ISSUE THREAD

**Issue by bill96012** [shedaniel/CustomSelectionBox-New#11]
just like the title says, break animation dosen't work.
only tested in 1.14 version.

fabric version - 0.4.6 build 141
mod version - 3.2.0

video:
https://streamable.com/hjgli

**Comment by shedaniel** [comment]
Oops I forgot to remove the option as the functionality has been removed when I moved to VoxelShape

**Comment by Dalevridge** [comment]
Moved to what? Sorry but I'm not following, I'd like to have this option back, will you update it?

**Comment by shedaniel** [comment]
It is now not possible to add this feature as 1.13 added a feature to render the bounding box in detail
