### ISSUE TITLE
java.lang.ClassCastException: net.minecraft.util.math.EntityRayTraceResult cannot be cast to net.minecraft.util.math.BlockRayTraceResult

### ISSUE THREAD

**Issue by jakey1995abc** [shedaniel/CustomSelectionBox-New#13]
"The game crashed whilst unexpected error
Error: java.lang.ClassCastException: net.minecraft.util.math.EntityRayTraceResult cannot be cast to net.minecraft.util.math.BlockRayTraceResult"

 

When looking at invisible entities (armour stands) for floating text on servers.

Issue is for latest 1.14.2 version of this mod.

**Comment by shedaniel** [comment]
Forge or fabric

**Comment by jakey1995abc** [comment]
Forge

**Comment by shedaniel** [comment]
Fixed in 1.4.8
