### ISSUE TITLE
CSB 5.0.1 for Fabric MC 1.16.1 doesn't draw selection box.

### ISSUE THREAD

**Issue by JillSwift** [shedaniel/CustomSelectionBox-New#16]
Everything works except… 
![2020-06-29_07 51 13](https://user-images.githubusercontent.com/5390031/86017047-cd83c800-b9e0-11ea-8604-3f15c047ca17.png)

Mods:
  [✔️] adabraniummod-1.1.4.1
  [✔️] antighost-1.16-fabric0.13.1-1.1.1
  [✔️] appleskin-mc1.16-fabric-1.0.11
  [✔️] Autofish-0.8.6-fabric-mc1.16
  [✔️] bambootweaks-2.0.0+1.16.1
  [✔️] BBOutlineReloaded-2.2-1.16.1-fabric
  [✔️] beem-1.3.1
  [✔️] beenfo-1.16-fabric0.13.1-1.0.3
  [✔️] better-signs-and-frames-mc-1.16.1-0.6.1
  [✔️] bunch-o-trinkets-1.0.1
  [✔️] canvas-mc116-1.0.716
  [✔️] clear-skies-mc116-1.3.38
  [✔️] cmdkeybind-1.4.3-1.16
  [✔️] craftingpad-1.16-fabric0.13.1-1.0.4
  [✔️] critical-flight-details-1.1.2
  [✔️] CustomSelectionBox-5.0.1
  [✔️] dark-loading-screen-1.3.0
  [✔️] diggusmaximus-1.2.11-1.16
  [✔️] EnchantedToolTips-1.3.1-1.16
  [✔️] exotic-blocks-mc116-1.4.138
  [✔️] exotic-matter-mc116-2.3.338
  [✔️] expandedstorage-5.2.11+1.16
  [✔️] fabric-api-0.14.0+build.371-1.16
  [✔️] fabric-furnaces-1.3.0-1.16.1
  [✔️] fabric-language-kotlin-1.3.71+build.1
  [✔️] fabricmod_VoxelMap-1.10.1_for_1.16
  [✔️] facility-mc116-0.9.144
  [✔️] grid-1.16-fabric0.13.1-1.5
  [✔️] HealthOverlay-1.16.1-3.5.10
  [✔️] Hwyla-fabric-1.16.1-1.9.22-75
  [✔️] InventorySorter-1.6.7-1.16
  [✔️] linkedstorage-1.3.2-1.16
  [✔️] mcf-reap-1.4.0-1.16
  [✔️] modmenu-1.12.2+build.17
  [✔️] mousewheelie-1.4.16+mc1.16-rc1
  [✔️] Mycommands-1.16.1-17
  [✔️] noncorrelatedextras-0.3.2+1.16
  [✔️] orderly-2.0.0-alpha.10-1.16
  [✔️] phosphor-fabric-mc1.16.1-0.6.0+build.7
  [✔️] RebornCore-1.16-4.3.1+build.35
  [✔️] RingOfGrowth-Fabric_1.16.1-1.0.18
  [✔️] RingOfMiner-Fabric_1.16.1-1.0.15
  [✔️] RingsOfAscension-1.16.1-1.0.1
  [✔️] RoughlyEnoughItems-4.5.5
  [✔️] rswires-4.8.0
  [✔️] simplepipes-all-0.4.0
  [✔️] slotlink-0.2+minecraft-1.16.1
  [✔️] SolidWorlds-mod-1.1.0+1.16
  [✔️] TechReborn-1.16-3.4.2+build.48
  [✔️] tinyfuel-fabric-0.2.1
  [✔️] torcherino-2.11.67+1.16-rc1
  [✔️] trinkets-2.6.2
  [✔️] VarLightFabric-1.16-1.4.1
  [✔️] WardBlocks-Fabric_1.16.1-1.0.13
  [✔️] WI-Zoom-1.2-MC1.16.1
  [✔️] worldedit-fabric-mc1.16.1-7.2.0-beta-01
  [✔️] XEnchantFabric-1.0.6

**Comment by shedaniel** [comment]
can you reproduce this with just custom selection box?

**Comment by JillSwift** [comment]
Ah, my bad. I should have checked that first.
Canvas Renderer was the problem.
CSB Works fine when Canvas isn't loaded.
